#!/bin/bash


#script guard
if [ ! "$0" == "./sbin/$(basename $0)" ]; then
        echo
        echo Must be invoked as ./sbin/$(basename $0)
        echo
        exit 1
fi


SD_CARD_DIR=sd_card_files/
BOOT_IMG_DIR=boot_image/
BIF_FILE=BOOT.bif

BOOTLOADER="[bootloader]$(readlink -f $BOOT_IMG_DIR/FSBL.elf)"
SYSTEM_BIT=$(readlink -f $BOOT_IMG_DIR/system.bit)
U_BOOT=$(readlink -f $BOOT_IMG_DIR/u-boot.elf)

#echo "the_ROM_image:" >> $BOOT_IMG_DIR/$BIF_FILE

echo
echo -------------------------------
echo create BOOT.BIN
echo -------------------------------
echo

echo create $BOOT_IMG_DIR/$BIF_FILE
echo
echo -n -e "the_ROM_image:
{			
	$BOOTLOADER	
	$SYSTEM_BIT	
	$U_BOOT		
}" > $BOOT_IMG_DIR/$BIF_FILE

echo bootgen -image $BOOT_IMG_DIR/$BIF_FILE -w on -o $SD_CARD_DIR/BOOT.BIN  
echo
bootgen -image $BOOT_IMG_DIR/$BIF_FILE -w on -o $SD_CARD_DIR/BOOT.BIN  

