#!/bin/bash


#script guard
if [ ! "$0" == "./sbin/$(basename $0)" ]; then
        echo
        echo Must be invoked as ./sbin/$(basename $0)
        echo
        exit 1
fi

LOG=generate.log

echo
echo -------------------------------
echo clean all
echo -------------------------------
echo

echo cleaning ZedBoard_Linux_Design/hw/xps_proj
echo

cd ZedBoard_Linux_Design/hw/xps_proj

make -f system.make clean

cd ../../../



DIRS="u-boot-digilent linux-digilent boot_image sd_card_files"

for d in $DIRS; do
	if [ -d $d ];then
		echo cleaning $d
		echo

		rm -rf $d
	fi
done

echo clean logs
echo
rm $LOG
