#!/bin/bash


#script guard
if [ ! "$0" == "./sbin/$(basename $0)" ]; then
        echo
        echo Must be invoked as ./sbin/$(basename $0)
        echo
        exit 1
fi

LOG=generate.log

echo
echo -------------------------------
echo clean files
echo -------------------------------
echo

echo clean files in boot_image and sd_card_files
echo

DIRS="boot_image sd_card_files"

for d in $DIRS; do
	if [ -d $d ];then
		echo cleaning $d
		echo

		rm -rf $d/*
	fi
done

echo clean logs
echo
rm $LOG
