#!/bin/bash

#script guard
if [ ! "$0" == "./sbin/$(basename $0)" ]; then
        echo
        echo Must be invoked as ./sbin/$(basename $0)
        echo
        exit 1
fi

#get $XILINX and $XILINX_EDK environment variables
source /opt/Xilinx/14.7/ISE_DS/settings32.sh
export LM_LICENSE_FILE=1700@ekleer

CONFIG_DIR=conf

echo
echo -------------------------------
echo create devicetree.dtb 
echo -------------------------------
echo



if [ -d linux-digilent ]; then
	cp $CONFIG_DIR/devicetree.dts linux-digilent/arch/arm/boot/dts/digilent-zed.dts 
	./linux-digilent/scripts/dtc/dtc -I dts -O dtb -o sd_card_files/devicetree.dtb linux-digilent/arch/arm/boot/dts/digilent-zed.dts
else
	echo not generating device tree. Kernel directory doesn\'t exist
	echo
fi

echo
