#!/bin/bash

#script guard
if [ ! "$0" == "./sbin/$(basename $0)" ]; then
        echo
        echo Must be invoked as ./sbin/$(basename $0)
        echo
        exit 1
fi

#get $XILINX and $XILINX_EDK environment variables
source /opt/Xilinx/14.7/ISE_DS/settings32.sh
export LM_LICENSE_FILE=1700@ekleer

SD_CARD_DIR=sd_card_files/
DRIVER_DIR=driver/
MAKE="make ARCH=arm CROSS_COMPILE=arm-xilinx-linux-gnueabi-"



echo
echo -------------------------------
echo create driver
echo -------------------------------
echo


if [ ! -d driver ]; then
	echo driver directory doesn\'t exist. Skipping...
	exit 0;
fi

cd $DRIVER_DIR 
$MAKE clean
$MAKE
cd ..
echo
cp -v $DRIVER_DIR/superip.ko $SD_CARD_DIR/superip.ko
echo
