#!/bin/bash

#script guard
if [ ! "$0" == "./sbin/$(basename $0)" ]; then
        echo
        echo Must be invoked as ./sbin/$(basename $0)
        echo
        exit 1
fi

#get $XILINX and $XILINX_EDK environment variables
source /opt/Xilinx/14.7/ISE_DS/settings32.sh
export LM_LICENSE_FILE=1700@ekleer


BOOT_IMG_DIR=boot_image/


echo
echo -------------------------------
echo generate system.bit
echo -------------------------------
echo


cd ZedBoard_Linux_Design/hw/xps_proj

make -f system.make bits

cd ../../../

echo
cp -v ZedBoard_Linux_Design/hw/xps_proj/implementation/system.bit $BOOT_IMG_DIR
echo
