#!/bin/bash

#script guard
if [ ! "$0" == "./sbin/$(basename $0)" ]; then
        echo
        echo Must be invoked as ./sbin/$(basename $0)
        echo
        exit 1
fi

#get $XILINX and $XILINX_EDK environment variables
source /opt/Xilinx/14.7/ISE_DS/settings32.sh
export LM_LICENSE_FILE=1700@ekleer

SD_CARD_DIR=sd_card_files

mkdir -p $SD_CARD_DIR

echo
echo -------------------------------
echo create zImage 
echo -------------------------------
echo


if [ ! -d linux-digilent ]; then
	git clone https://github.com/Digilent/linux-digilent
fi
cd linux-digilent
make ARCH=arm CROSS_COMPILE=arm-xilinx-linux-gnueabi- digilent_zed_defconfig
make ARCH=arm CROSS_COMPILE=arm-xilinx-linux-gnueabi-
cd ..

cp -v linux-digilent/arch/arm/boot/zImage $SD_CARD_DIR/

echo
